name: (NuGet) MyGet Release

on:
  workflow_run:
    workflows: [ "Build" ]
    types:
      - completed
jobs:
  configuration:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'pull_request' }}
    runs-on: ubuntu-latest
    outputs:
      MYGET_ENABLED: ${{ steps.config.outputs.MYGET_ENABLED }}
    steps:
      - name: Get MyGet status
        id: config
        run: |
          echo "::set-output name=MYGET_ENABLED::${{ secrets.MYGET_ENABLED }}"

  myget_release:
    name: MyGet Release
    needs: [ "configuration" ]
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event != 'pull_request' && needs.configuration.outputs.MYGET_ENABLED == 'true' }}
    runs-on: ubuntu-latest
    env:
      # Nuget Setup
      NUGET_VERSION: 'latest'
      NUGET_OUTPUT: ${{ github.workspace }}/nuget/

      # Project Setup
      PROJECT_NAME: 'Cogworks.ContentGuard'

      # MyGet Feed settings
      MYGET_TOKEN: ${{ secrets.MYGET_TOKEN }}
      MYGET_FEED: https://www.myget.org/F/cogworks-packages/auth/${{ secrets.MYGET_TOKEN }}/api/v3/index.json

    steps:
      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: master
          fetch-depth: 0

      - name: Get version
        shell: bash
        run: |
          tag_check=$(git describe --exact-match `git rev-parse HEAD` | head -1)
          echo "VERSION=$tag_check" >> $GITHUB_ENV

      - name: Download a single artifact
        uses: aochmann/actions-download-artifact@1.0.2
        with:
          name: build_${{ env.PROJECT_NAME }}.${{ env.VERSION }}
          path: ${{ env.NUGET_OUTPUT }}

      - name: Configure NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-version: ${{ env.NUGET_VERSION }}

      - name: Push to MyGet Feed
        shell: bash
        working-directory: ${{ env.NUGET_OUTPUT }}
        run: |
          for nugetFile in ./*.nupkg
          do
            nuget push $nugetFile ${{ env.MYGET_TOKEN }} -Source ${{ env.MYGET_FEED }}
          done
